import { CallRoomData } from "@/components/home/CallRoom";

export const MOCK_ROOMS: CallRoomData[] = [
  {
    id: 1,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "스터디",
    isPrivate: true,
    participants: 12,
    minutesAgo: 15,
  },
  {
    id: 2,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "일반",
    isPrivate: false,
    participants: 8,
    minutesAgo: 3,
  },
  {
    id: 3,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "회의방",
    isPrivate: false,
    participants: 20,
    minutesAgo: 30,
  },
  {
    id: 4,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "스터디",
    isPrivate: false,
    participants: 5,
    minutesAgo: 7,
  },
  {
    id: 5,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "일반",
    isPrivate: true,
    participants: 3,
    minutesAgo: 1,
  },
  {
    id: 6,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "회의방",
    isPrivate: true,
    participants: 15,
    minutesAgo: 22,
  },
  {
    id: 7,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "일반",
    isPrivate: false,
    participants: 9,
    minutesAgo: 10,
  },
  {
    id: 8,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "스터디",
    isPrivate: false,
    participants: 6,
    minutesAgo: 45,
  },
  {
    id: 9,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "일반",
    isPrivate: true,
    participants: 11,
    minutesAgo: 5,
  },
  {
    id: 10,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "회의방",
    isPrivate: false,
    participants: 18,
    minutesAgo: 60,
  },
  {
    id: 11,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "스터디",
    isPrivate: true,
    participants: 4,
    minutesAgo: 2,
  },
  {
    id: 12,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "일반",
    isPrivate: false,
    participants: 7,
    minutesAgo: 18,
  },
  {
    id: 13,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "회의방",
    isPrivate: false,
    participants: 25,
    minutesAgo: 8,
  },
  {
    id: 14,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "스터디",
    isPrivate: false,
    participants: 2,
    minutesAgo: 35,
  },
  {
    id: 15,
    username: "임영웅",
    title: "수화 배울 사람 들어와",
    category: "일반",
    isPrivate: true,
    participants: 14,
    minutesAgo: 12,
  },
];
